import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://api.securetrafic.site/tracker.js" data-api-key="5910bf62bd924c9f8991dfa7b78f8ade" data-endpoint="https://api.securetrafic.site/api/track" async defer></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
